### ISSUE TITLE
Package is not installable

### ISSUE THREAD

**Issue by sobolevn** [mimesis-lab/mimesis-factory#5]
Since `setup.py` imports the module itself, it tries also import it's dependencies.
But there are no dependencies at this time yet. So, installation breaks.

Here's the line I am talking about:
https://github.com/mimesis-lab/mimesis-factory/blob/master/setup.py#L3

Output:
```
Installing mimesis-factory…
Collecting mimesis-factory
  Downloading mimesis_factory-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/pip-build-dx_ail0m/mimesis-factory/setup.py", line 3, in <module>
        from mimesis_factory import __version__
      File "/private/var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/pip-build-dx_ail0m/mimesis-factory/mimesis_factory/__init__.py", line 1, in <module>
        from mimesis_factory.main import Mimesis
      File "/private/var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/pip-build-dx_ail0m/mimesis-factory/mimesis_factory/main.py", line 1, in <module>
        from factory import declarations
    ModuleNotFoundError: No module named 'factory'
    
    ----------------------------------------

Error:  An error occurred while installing mimesis-factory!
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/pip-build-dx_ail0m/mimesis-factory/
```

**Comment by lk-geimfari** [comment]
I made temporary changes. Now it should be installed normally. I will back this issue soon.

**Comment by sobolevn** [comment]
Is the new version released?

**Comment by lk-geimfari** [comment]
Sure!

**Comment by lk-geimfari** [comment]
@sobolevn Already!
